"""Agregar columnas faltantes

Revision ID: 259d78e0d4cd
Revises: 
Create Date: 2025-12-24 20:22:39.053190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259d78e0d4cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('labor', sa.Float(), nullable=True),
    sa.Column('parts', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('lemon_customer_id', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('change', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('client_ibfk_1'), type_='foreignkey')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('job_ibfk_1'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('job_ibfk_1'), 'workshop', ['workshop_id'], ['id'])
        batch_op.drop_column('priority')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('client_ibfk_1'), 'workshop', ['workshop_id'], ['id'])

    op.drop_table('job_log')
    op.drop_table('subscription')
    op.drop_table('estimate')
    # ### end Alembic commands ###
