"""add checkout_id to pending_subscription

Revision ID: 8df6df041153
Revises: bd365be196fd
Create Date: 2026-01-02 13:47:00.527703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df6df041153'
down_revision = 'bd365be196fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_id', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_subscription', schema=None) as batch_op:
        batch_op.drop_column('checkout_id')

    # ### end Alembic commands ###
