"""whop subscription

Revision ID: bd365be196fd
Revises: f2e6d52cc3dd
Create Date: 2026-01-02 13:22:37.466468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd365be196fd'
down_revision = 'f2e6d52cc3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_subscription', schema=None) as batch_op:
        batch_op.alter_column('workshop_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('plan',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whop_order_id', sa.String(length=100), nullable=True))
        batch_op.drop_column('lemon_customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lemon_customer_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('whop_order_id')

    with op.batch_alter_table('pending_subscription', schema=None) as batch_op:
        batch_op.alter_column('plan',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('workshop_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
