"""Add currency and rejected to Estimate

Revision ID: f2e6d52cc3dd
Revises: 259d78e0d4cd
Create Date: 2025-12-24 22:03:52.075376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e6d52cc3dd'
down_revision = '259d78e0d4cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('rejected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimate', schema=None) as batch_op:
        batch_op.drop_column('rejected')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
